name: 'cloudformation-guard-action'
description: 'Run cfn-guard compliance tool against your repository'
author: 'Dagen Brock'
branding:
    icon: 'terminal'
    color: 'yellow'
inputs:
    cfn_directory:
        description: 'Sub Directory of cloudformation templates'
        required: true
        default: 'cloudformation'
runs:
    using: 'docker'
    image: './Dockerfile'
